INSERT INTO USER (ID, USERNAME, NAME, AGE, BALANCE) VALUES (1, 'ACCOUNT1', '张三', 20, 100.00);
INSERT INTO USER (ID, USERNAME, NAME, AGE, BALANCE) VALUES (2, 'ACCOUNT2', '李四', 28, 180.00);
INSERT INTO USER (ID, USERNAME, NAME, AGE, BALANCE) VALUES (3, 'ACCOUNT3', '王五', 32, 280.00);